id: PEFD920E5
initial_creation_type: ocr
source_metadata:
  volumes:
    eadf1ca0f11c4cde99607381bb4e19b6:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: རྡོ་རྗེ་མཁའ་འགྲོ་རྣལ་འབྱོར་མའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
